### ISSUE TITLE
EOFError: Ran out of input while loading VQVAETokenizer  

### ISSUE THREAD

**Issue by PytaichukBohdan** [THUDM/CogView#27]
It happens both locally and on the colab
Full traceback:
`Traceback (most recent call last):
  File "generate_samples.py", line 326, in <module>
    main()
  File "generate_samples.py", line 318, in main
    tokenizer = prepare_tokenizer(args)
  File "generate_samples.py", line 276, in prepare_tokenizer
    tokenizer = get_tokenizer(args)
  File "/home/bohdan_pytaichuk/CogView/CogViewMain/CogView/data_utils/unified_tokenizer.py", line 202, in get_tokenizer
    get_tokenizer.tokenizer = UnifiedTokenizer(
  File "/home/bohdan_pytaichuk/CogView/CogViewMain/CogView/data_utils/unified_tokenizer.py", line 30, in __init__
    self.img_tokenizer = VQVAETokenizer(model_path=img_tokenizer_path, device=self.device)
  File "/home/bohdan_pytaichuk/CogView/CogViewMain/CogView/data_utils/vqvae_tokenizer.py", line 38, in __init__
    ckpt = torch.load(model_path, map_location=torch.device(device))
  File "/home/bohdan_pytaichuk/env/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/bohdan_pytaichuk/env/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
`

**Comment by PytaichukBohdan** [comment]
Fixed, found another link that downloaded the model properly
