### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by metaphorz** [THUDM/CogView#35]
I found a colab file reference in a closed issue. The last cell (inference) shows this error. Does anyone know of a solution or a more recent Colab noteboook? The web-based version of Cogview works but takes a while to process queued requests.

`/content/CogView
Traceback (most recent call last):
  File "generate_samples.py", line 28, in <module>
    from utils import Timers
  File "/content/CogView/utils.py", line 25, in <module>
    from fp16 import FP16_Optimizer
  File "/content/CogView/fp16/__init__.py", line 15, in <module>
    from .fp16util import (
  File "/content/CogView/fp16/fp16util.py", line 21, in <module>
    import mpu
  File "/content/CogView/mpu/__init__.py", line 35, in <module>
    from .layers import ColumnParallelLinear
  File "/content/CogView/mpu/layers.py", line 28, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm
ModuleNotFoundError: No module named 'apex'
`

**Comment by Sleepychord** [comment]
It seems the apex package is not installed in the environment. @johnpaulbin built the Colab, maybe you could ask him for help?

**Comment by johnpaulbin** [comment]
Hey there, the colab *should* automatically install apex, make sure you have a colab Pro subscription (with HighRam Runtime) and run all the required cells first.

**Comment by jesimon** [comment]
Anyone figure this out yet?
